apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: petclinic-pipeline
  namespace: petclinic-1
spec:
  params:
    - description: Image application tag
      name: tag
      type: string
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: 'https://github.com/sbem44/spring-petclinic.git'
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: source
          workspace: source-data
    - name: maven
      params:
        - name: GOALS
          value:
            - clean
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SUBDIRECTORY
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: source-data
    - name: buildah
      params:
        - name: IMAGE
          value: 'quay.io/rheembertuzz/sandbox:$(params.tag)'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - maven
      taskRef:
         kind: Task
         name: buildah
      workspaces:
        - name: source
          workspace: source-data
        - name: dockerconfig
          workspace: docker-config
    - name: update-deployment-image
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: GIT_USER_NAME
          value: Tekton
        - name: GIT_USER_EMAIL
          value: tekton@sbem44.com
        - name: GIT_SCRIPT
          value: |
            whoami && echo "HOME: $HOME" && git clone git@github.com:sbem44/gitops-sandbox.git && cd gitops-sandbox/app/petclinic-1 && sed -i "s|\(image: .*/.*:\).*|\1$(params.tag)|" deployment.yaml && git add . && git commit -m "[Tekton Bot] trigger deploy" && git push
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: git-cli
        #params:
        #  - name: kind
        #    value: task
        #  - name: name
        #    value: git-cli
       #   - name: namespace
        #    value: openshift-pipelines
       # resolver: cluster
      workspaces:
        - name: ssh-directory
          workspace: ssh-creds
        - name: source
          workspace: source-data-gitops
  workspaces:
    - name: source-data
    - name: docker-config
    - name: source-data-gitops
    - name: ssh-creds
