apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-app-sandbox
  namespace: openshift-gitops
spec:
  generators:
    - git:
        directories:
          - path: 'app/*'
        repoURL: 'https://github.com/sbem44/gitops-sandbox.git'
        revision: HEAD
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      destination:
        namespace: '{{.path.basename}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{.path.path}}'
        repoURL: 'https://github.com/sbem44/gitops-sandbox.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false